[package]
name = "abigen-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.19"
ethers = "2.0.8"
eyre = "0.6.8"
